import React, { useEffect, useRef, useState } from 'react';
import { View, Text, StyleSheet, Alert } from 'react-native';
import { RTCView } from 'react-native-webrtc';
import { GradientBackground } from '../components/GradientBackground';
import { PrimaryButton } from '../components/PrimaryButton';
import { colors } from '../theme/colors';
import { WebRtcService } from '../services/WebRtcService';
export const VideoCallScreen = ({ go, pendingOffer, setPendingOffer }: { go: (s: any) => void; pendingOffer: any; setPendingOffer: (o: any) => void }) => {
  const svc = useRef(new WebRtcService()).current; const [local, setLocal] = useState<any>(); const [remote, setRemote] = useState<any>(); const [mic, setMic] = useState(true); const [cam, setCam] = useState(true); const [state, setState] = useState('Connecting media…');
  useEffect(() => { const u1 = svc.on('localStream', (s: any) => setLocal(s)); const u2 = svc.on('remoteStream', (s: any) => { setRemote(s); setState('Connected peer video'); }); const u3 = svc.on('error', (e: string) => Alert.alert('WebRTC', e)); (async () => { try { await svc.init(); if (pendingOffer) { await svc.handleInitialOffer(pendingOffer); setPendingOffer(null); setState('Answer sent'); } else { await svc.startCall(); setState('Offer sent'); } } catch (e: any) { Alert.alert('Media error', String(e?.message || e)); go('chat'); } })(); return () => { u1(); u2(); u3(); }; }, []);
  const end = () => { svc.close(true); go('chat'); };
  return <GradientBackground><View style={styles.root}><View style={styles.remote}>{remote ? <RTCView streamURL={remote.toURL()} style={styles.video} objectFit="cover" /> : <View style={styles.wait}><Text style={styles.waitText}>{state}</Text><Text style={styles.sub}>Waiting for LAN peer…</Text></View>}</View><View style={styles.local}>{local && cam ? <RTCView streamURL={local.toURL()} style={styles.video} objectFit="cover" mirror /> : <Text style={styles.sub}>Camera off</Text>}</View><View style={styles.bar}><PrimaryButton title={mic ? 'Mute' : 'Unmute'} variant="secondary" onPress={() => { svc.toggleMic(!mic); setMic(!mic); }} style={styles.ctrl} /><PrimaryButton title={cam ? 'Camera off' : 'Camera on'} variant="secondary" onPress={() => { svc.toggleCamera(!cam); setCam(!cam); }} style={styles.ctrl} /><PrimaryButton title="Switch" variant="secondary" onPress={() => svc.switchCamera()} style={styles.ctrl} /></View><PrimaryButton title="End call" variant="danger" onPress={end} style={{ marginTop: 12 }} /></View></GradientBackground>;
};
const styles = StyleSheet.create({ root: { flex: 1, padding: 16, paddingTop: 44 }, remote: { flex: 1, borderRadius: 28, overflow: 'hidden', backgroundColor: '#050B14', borderColor: colors.line, borderWidth: 1 }, video: { width: '100%', height: '100%' }, wait: { flex: 1, alignItems: 'center', justifyContent: 'center' }, waitText: { color: colors.text, fontSize: 22, fontWeight: '900' }, sub: { color: colors.muted, marginTop: 8, textAlign: 'center' }, local: { position: 'absolute', top: 72, right: 28, width: 116, height: 158, borderRadius: 22, overflow: 'hidden', backgroundColor: colors.card, alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: colors.cyan }, bar: { flexDirection: 'row', gap: 8, marginTop: 14 }, ctrl: { flex: 1 } });
